In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import sqlite3
import pandas as pd
from datetime import datetime

In [3]:
connection = sqlite3.connect("blog.db")
cursor = connection.cursor()

In [4]:
cursor.execute("""
CREATE TABLE IF NOT EXISTS blog_posts(
id INTEGER PRIMARY KEY AUTOINCREMENT,
title TEXT,
content TEXT,
author TEXT,
date TEXT
)
""")

connection.commit()

In [5]:
def add_blog(title, content, author):

    date = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    cursor.execute("""
    INSERT INTO blog_posts(title, content, author, date)
    VALUES (?, ?, ?, ?)
    """, (title, content, author, date))

    connection.commit()

    print("Blog Added Successfully")

In [6]:
add_blog(
    "Python Basics",
    "Python is an easy programming language.",
    "Karuna"
)

add_blog(
    "Machine Learning",
    "Machine learning is a subset of Artificial Intelligence.",
    "Karuna"
)

Blog Added Successfully
Blog Added Successfully

In [7]:
cursor.execute("SELECT * FROM blog_posts")

rows = cursor.fetchall()

df = pd.DataFrame(
    rows,
    columns=[
        "ID",
        "Title",
        "Content",
        "Author",
        "Date"
    ]
)

df

,ID,Title,Content,Author,Date
0,1,Python Basics,Python is an easy programming language.,Karuna,07-07-2026 17:41:23
1,2,Machine Learning,Machine learning is a subset of Artificial Int...,Karuna,07-07-2026 17:41:23

In [8]:
keyword = "Python"

cursor.execute("""
SELECT * FROM blog_posts
WHERE title LIKE ?
OR content LIKE ?
""",('%'+keyword+'%','%'+keyword+'%'))

result = cursor.fetchall()

pd.DataFrame(
    result,
    columns=[
        "ID",
        "Title",
        "Content",
        "Author",
        "Date"
    ]
)

,ID,Title,Content,Author,Date
0,1,Python Basics,Python is an easy programming language.,Karuna,07-07-2026 17:41:23

In [9]:
cursor.execute("""
UPDATE blog_posts
SET content=?
WHERE id=1
""",("Python is one of the easiest programming languages.",))

connection.commit()

print("Updated Successfully")

Updated Successfully

In [10]:
cursor.execute("""
DELETE FROM blog_posts
WHERE id=2
""")

connection.commit()

print("Deleted Successfully")

Deleted Successfully

In [11]:
cursor.execute("SELECT * FROM blog_posts")

rows = cursor.fetchall()

pd.DataFrame(
    rows,
    columns=[
        "ID",
        "Title",
        "Content",
        "Author",
        "Date"
    ]
)

,ID,Title,Content,Author,Date
0,1,Python Basics,Python is one of the easiest programming langu...,Karuna,07-07-2026 17:41:23

In [12]:
connection.close()